### PR TITLE
update quote and syn to 1.0, rust to 2018 and run cargo fmt

### LINKED ISSUE #43: Please update to syn/quote/proc-macro2 version 1.0
As the title says

### PR DESCRIPTION
**Pull request by jakobhellermann**
fixes #43

This PR will change the MSRV because quote 1.0 needs rust 1.31.

### CODE REVIEW

**Comment by mcarton** [comment]
Thanks, but please remove commit b9d80ad and do not run rustfmt in `tests`. Most of those tests are copy-pasted directly from rustc and since rustfmt wasn't used there, this change makes it harder to check the difference between the original tests and the tests included here.

Also, as specified in #43, this will require a bump to 2.0, which I am planning, but I was considering doing some other changes before.

**Comment by jjakobh** [comment]
> Also, as specified in #43, this will require a bump to 2.0, which I am planning, but I was considering doing some other changes before.

Should I just leave this open and rebase when changes are made to master?

**Comment by nox** [comment]
> Also, as specified in #43, this will require a bump to 2.0, which I am planning, but I was considering doing some other changes before.

What other changes are you planning on? Will that take time? Do you need help? It would be nice if this could land and we could live in a post-syn-1 world.

**Comment by nox** [comment]
`derivative` is one of the last crates in the Servo crate tree to still use syn 0.15. Any ETA for a new release with this PR?

**Comment by mcarton** [comment]
Sorry for the long delay! I have now merged #50 which is an update of this PR.

**Pull request closed without merging**
