### PR TITLE
Fix a clippy warning when using clone_from = "true" 

### LINKED ISSUE #74: clippy warns when using clone_from = "true"
**Describe the bug**

clippy warns when using `clone_from = "true"`

**To Reproduce**

```rust
use derivative::Derivative;

#[derive(Derivative)]
#[derivative(Clone(clone_from = "true"))]
pub struct Foo {}

fn main() {}
```

```
cargo clippy 
    Checking test-rs v0.1.0 (/home/xxx/dev/test-rs)
warning: unneeded `return` statement
 --> src/main.rs:3:10
  |
3 | #[derive(Derivative)]
  |          ^^^^^^^^^^
  |
  = note: `#[warn(clippy::needless_return)]` on by default
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_return
  = note: this warning originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

warning: 1 warning emitted

    Finished dev [unoptimized + debuginfo] target(s) in 0.14s
```

**Expected behavior**

No warning

**Version (please complete the following information):**

Please include the output of the following commands, and any other version you think is relevant:

```sh
rustup 1.21.1 (7832b2ebe 2019-12-20)
cargo 1.44.1 (88ba85757 2020-06-11)
rustc 1.44.1 (c7087fe00 2020-06-17)
```
 - Version of `derivative`:
```
name = "derivative"
version = "2.1.1"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "cb582b60359da160a9477ee80f15c8d784c477e69c217ef2cdd4169c24ea380f"
```

### PR DESCRIPTION
**Pull request by TeXitoi**
I also cleaned clippy warning in test, activated `cargo clippy --all-targets` to have clippy running on tests, and some fmt in the modified files.

Each modification is in a different commit, so I can remove some if you prefer.

Fixes #74

### CODE REVIEW

**Comment by TeXitoi** [comment]
Any feedbacks? I'd like to add clippy on CI, and I'm only blocked by this warning.

**Comment by TeXitoi** [comment]
Any news? @mcarton do you need help in maintaining this crate?

**Comment by mcarton** [comment]
Thanks, I cherry-picked some commits in #81 and released it as v2.1.3.
I didn't merge this PR because it now had conflicts and I don't want to run rustfmt on the tests folder, as most of those tests are copied from rustc and I want to preserve them as much as possible.

**Comment by TeXitoi** [comment]
Thanks

**Pull request closed without merging**
